### ISSUE TITLE
Unable to load PayForm storyboard from framework

### ISSUE THREAD

**Issue by CBDev1** [Beanstream/beanstream-ios-payform#3]
When I try to run the sample code in the README, I get this error:

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'PayForm' in bundle NSBundle </Users/{USERNAME}/Library/Developer/CoreSimulator/Devices/B86BCF6C-913C-4509-9946-5CACC35CB812/data/Containers/Bundle/Application/6240778F-24EB-439C-938F-6ACC84FA9827/payformtest.app/Frameworks/PayForm.framework> (loaded)'

I tried this in a new/empty swift project. The PayForm framework was added through cocoapods as directed in the README.

**Comment by svenresch** [comment]
If you want I'd be happy to look at your project to see if I can find the issue. Conversely, I have a test project that pulls in PayForm via CocoaPods that I could tar up and send you to use to compare with.

BTW... I just updated to Xcode 8 and am considering if updating the code base to Swift 2.3 or 3.0 is best. Do you have any thoughts on the matter?

**Comment by CBDev1** [comment]
I uploaded the sample that crashes here: https://github.com/CBDev1/PayFormSimpleTest

My opinion is objective-c for best compatibility. Don't have to rely on a specific xcode version, don't have to keep updating syntax, etc ;o) As for which Swift version, I have no opinion since I am personally waiting for ABI stability before updating any of my code

**Comment by dlight-bean** [comment]
Current workaround

1. In XCode, click on _**Pods > Pods > PayForm > Resources > PayForm.storyboard**_
2. Under Target Membership, check **_PayForm_**
3. Clean and build

**Comment by dlight-bean** [comment]
0.3.2 should resolve this issue.

**Comment by dlight-bean** [comment]
Closing as user appears to be unblocked with the latest fix

**Comment by CBDev1** [comment]
Unfortunately this did not solve my issue, and the workaround does not work anymore.

New error, it appears it is now looking for the storyboard in the main bundle instead of the PayForm cocoa pod:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'PayForm' in bundle NSBundle </Users/{USERNAME}/Library/Developer/CoreSimulator/Devices/B86BCF6C-913C-4509-9946-5CACC35CB812/data/Containers/Bundle/Application/3074A088-3C8B-4C11-A556-CD603DBDE2B6/{APPNAME}.app> (loaded)'

**Comment by CBDev1** [comment]
Never mind, my bug. I forgot to change the bundle back after updating to the newest version of PayForm like it shows in the Readme:
let bundle = NSBundle.init(forClass: PayFormViewController.classForCoder())

**Comment by CBDev1** [comment]
Hmmm, not fixed after all. In order to get it to work in my project, I also need to change this line in the PayForm library.
PayFormViewController.swift line 131
From:
`let storyboard = UIStoryboard(name: "PayForm", bundle: nil)`
To:
`let storyboard = UIStoryboard(name: "PayForm", bundle: NSBundle(forClass: self.classForCoder))`
